parent: $LVSR/exp/wsj/configs/wsj_prior_conv.yaml
training:
    rules:
        - momentum
        - adadelta
    scale: 0.1
    decay_rate: 0.95
    epsilon: 1.0e-8
net:
    use_states_for_readout: True
    bottom:
        activation: !!python/object/apply:blocks.bricks.Rectifier []
# JCh: These options were removed in 1.2016. They should be overriden in
# Configurations that are based on this one
#
# data:
#     preprocess_text: True
#     preprocess_features: log_spectrogram
