parent: $LVSR/exp/wsj/configs/wsj_jan_new.yaml
net:
    bottom:
        activation: !!python/object/apply:blocks.bricks.Rectifier []
        dims: []

    enc_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    dims_bidir: [256, 256, 256]
    subsample: [1, 1, 1]

