parent: $LVSR/lvsr/configs/prototype.yaml
data:
    dataset_filename: wsj.h5

    name_mapping:
        train: train_si284
        valid: test_dev93
        test:  test_eval92

    sources_map:
        recordings: recordings
        labels: labels
        uttids: uttids

    normalization: wsj_norm.pkl
net:
    dim_dec: 250
    dims_bidir: [250]
    bottom:
        dims: [250]

    attention_type: content_and_conv
    conv_n: 100
    prior:
        initial_begin: 0
        initial_end: 200
        min_speed: 6
        max_speed: 11
    dec_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    enc_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
training:
    scale: 0.004
initialization:
    /recognizer:
        rec_weights_init:
            !!python/object/apply:blocks.initialization.IsotropicGaussian [0.1]
