data:
    normalization: timit2_norm.pkl
    recordings_source: recordings
    labels_source: labels
net:
    dec_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    enc_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
initialization:
    /recognizer:
        rec_weights_init:
            !!python/object/apply:blocks.initialization.IsotropicGaussian [0.1]
