parent: $LVSR/lvsr/configs/timit_bothgru.yaml
data:
    dataset: WSJ
    normalization: wsj_norm.pkl
net:
    dim_dec: 250
    dims_bidir: [250]
    dims_bottom: [250]
    attention_type: content_and_conv
    conv_n: 100
    prior:
        initial_begin: 0
        initial_end: 200
        min_speed: 6
        max_speed: 11
training:
    scale: 0.004
