parent: $LVSR/lvsr/configs/wsj_prior.yaml
data:
    max_length: 200000
    batch_size: 4
net:
    use_states_for_readout: True
    attention_type: content_and_conv
    conv_n: 100
training:
    scale: 0.0001

