parent: $LVSR/lvsr/configs/wsj_good_fbank.yaml
net:
    dims_bidir: [250, 250, 250]
    subsample: [1, 1, 2]
    post_merge_dims: [250]
    # 0.5 times respective settings from wsj_good_fbank.yaml
    prior:
        initial_begin: 0
        initial_end: 80
        min_speed: 2.4
        max_speed: 4.4

