parent: $LVSR/lvsr/configs/timit_bothgru_cumsum_250.yaml
data:
    dataset: WSJ
    max_length: 100000
    normalization: wsj_norm.pkl
net:
    attention_type: content_and_cumsum
    prior:
        initial_begin: 0
        initial_end: 200
        min_speed: 6
        max_speed: 11
