parent: $LVSR/lvsr/configs/wsj_good.yaml
data:
    dataset: WSJnew
    normalization: 
    recordings_source: fbank_dd
    labels_source: characters
    add_eos: True
    preprocess_text: False
    preprocess_features: False
    

