parent: $LVSR/lvsr/configs/prototype_speech.yaml
data:
    dataset_filename: timit.h5
    dataset_class: !!python/name:lvsr.datasets.h5py.H5PYAudioDatasetTimit

    name_mapping:
        train: train
        valid: dev
        test:  test

    sources_map:
        recordings: fbank40_dd
        labels: phones60
        uttids: uttids

    default_sources: [recordings, labels]

    max_length: 10000000000000
    normalization: ''

    add_eos: True
    prepend_eos: False

    sort_k_batches: ''
    batch_size: 1
    validation_batch_size: 64

initialization:
    /recognizer:
        weights_init:
            !!python/object/apply:blocks.initialization.IsotropicGaussian [0.01]
        biases_init:
            !!python/object/apply:blocks.initialization.Constant [0.0]
        rec_weights_init:
            !!python/object/apply:blocks.initialization.Orthogonal []
        initial_states_init:
            !!python/object/apply:blocks.initialization.IsotropicGaussian [0.001]

net:
    bottom:
        activation: !!python/object/apply:blocks.bricks.Rectifier []
        dims: []

    enc_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    dims_bidir: [256, 256, 256]
    subsample: [1, 1, 1]

    dec_transition: !!python/name:blocks.bricks.recurrent.GatedRecurrent
    dim_dec: 256
    dim_matcher: 512

    attention_type: content

    post_merge_dims: [256]
    post_merge_activation: !!python/object/apply:blocks.bricks.Maxout [2]

    use_states_for_readout: True

training:
    rules: [momentum, adadelta]
    scale: 1.0
    momentum: 0.0

    decay_rate: 0.95
    epsilon: 1.0e-8

    gradient_threshold: 1000.0
    num_batches: 100000000
    num_epochs: 100000
    patience:
        patience_factor: 1.5
        min_epochs: 10
    burn_in_steps: 0

stages:
    pretraining:
        number: 0
        data:
            batch_size: 8
        regularization:
            max_norm: 1.0
        training:
            num_epochs: 50
    main:
        number: 100
        regularization:
            adaptive_noise:
                model_cost_coefficient: 0.1
                init_sigma: 1.0e-12
        training:
            restart_from: _best_ll
            num_epochs: 500
    annealing:
        number: 200
        regularization:
            adaptive_noise:
                model_cost_coefficient: 0.1
                init_sigma: 1.0e-12
        training:
            epsilon: 1.0e-10
            restart_from: _best_ll
            num_epochs: 500
